// flow-typed signature: 8569f5ab1bb3b30508e56bd16d9b7d7f
// flow-typed version: <<STUB>>/reactstrap-pager_v^1.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactstrap-pager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactstrap-pager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactstrap-pager/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module 'reactstrap-pager/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module 'reactstrap-pager/config/polyfills' {
  declare module.exports: any;
}

declare module 'reactstrap-pager/dist/index' {
  declare module.exports: any;
}

declare module 'reactstrap-pager/dist/manifest' {
  declare module.exports: any;
}

declare module 'reactstrap-pager/dist/vendor' {
  declare module.exports: any;
}

declare module 'reactstrap-pager/src/index' {
  declare module.exports: any;
}

declare module 'reactstrap-pager/src/index.test' {
  declare module.exports: any;
}

declare module 'reactstrap-pager/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactstrap-pager/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'reactstrap-pager/config/jest/cssTransform'>;
}
declare module 'reactstrap-pager/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'reactstrap-pager/config/jest/fileTransform'>;
}
declare module 'reactstrap-pager/config/polyfills.js' {
  declare module.exports: $Exports<'reactstrap-pager/config/polyfills'>;
}
declare module 'reactstrap-pager/dist/index.js' {
  declare module.exports: $Exports<'reactstrap-pager/dist/index'>;
}
declare module 'reactstrap-pager/dist/manifest.js' {
  declare module.exports: $Exports<'reactstrap-pager/dist/manifest'>;
}
declare module 'reactstrap-pager/dist/vendor.js' {
  declare module.exports: $Exports<'reactstrap-pager/dist/vendor'>;
}
declare module 'reactstrap-pager/index' {
  declare module.exports: $Exports<'reactstrap-pager'>;
}
declare module 'reactstrap-pager/index.js' {
  declare module.exports: $Exports<'reactstrap-pager'>;
}
declare module 'reactstrap-pager/src/index.js' {
  declare module.exports: $Exports<'reactstrap-pager/src/index'>;
}
declare module 'reactstrap-pager/src/index.test.js' {
  declare module.exports: $Exports<'reactstrap-pager/src/index.test'>;
}
declare module 'reactstrap-pager/webpack.config.babel.js' {
  declare module.exports: $Exports<'reactstrap-pager/webpack.config.babel'>;
}
